<script src="{{ asset('assets/js/bootstrap.js') }}"></script>
<script src="{{ asset('assets/js/app.js') }}"></script>
<script src="{{ asset('assets/extensions/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('assets/extensions/jquery/jquery-ui.min.js') }}"></script>
<script src="{{ asset('assets/extensions/summernote/summernote-lite.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/summernote.js') }}"></script>
<script src="{{ asset('assets/extensions/choices.js/public/assets/scripts/choices.js') }}"></script>
<script src="{{ asset('assets/js/pages/form-element-select.js') }}"></script>
<script src="{{ asset('assets/extensions/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('assets/extensions/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>

<script src="{{ asset('assets/extensions/datetimepicker/moment.min.js') }}"></script>
<script src="{{ asset('assets/extensions/datetimepicker/bootstrap-datetimepicker.js') }}"></script>
<script src="{{ asset('assets/extensions/bootstrap-toggle/bootstrap-toggle.min.js') }}"></script>
<script src="{{ asset('assets/extensions/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/datatables.min.js') }}"></script>
<script src="{{ asset('assets/extensions/sortablejs/Sortable.min.js') }}"></script>
<script src="{{ asset('assets/extensions/nestable2/jquery.nestable.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/datatables.js') }}"></script>
<script src="{{ asset('assets/js/pages/jquery.twbsPagination.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/global.js') }}"></script>
<script src="{{ asset('assets/js/pages/dataTables.rowReorder.min.js') }}"></script>
<script src="{{ asset('assets/extensions/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/daterangepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/extensions/filepond.min.js') }}"></script>
<script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>