<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PurchaseOrderDetail extends Model
{

    protected $table = "purchase_order_detail";
    protected $primaryKey = 'id';
    public $incrementing = true;
    protected $keyType = 'integer';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'no_po',
        'purchase_order_id',
        'nama_barang',
        'link_barang',
        'estimasi_kg',
        'estimasi_harga',
        'status_follow_up',
        'nama_rek_transfer',
        'jumlah_transfer',
        'dp',
        'fullpayment',
        'foto_bukti_tf',
        'mutasi_check',
        'payment_method',
        'total_purchase',
        'foto_bukti_pembelian',
        'status_purchase',
        'notes',
        'hpp_mutasi_check',
        'wh_usa',
        'status_on_check',
        'wh_indo',
        'fix_weight',
        'fix_price',
        'status_barang_sampai',
        'qty',
        'estimasi_diskon',
        'total_estimasi',
        'asuransi',
        'jasa',
        'estimasi_notes',
        'kurang_bayar',
        'sku',
        'kurir_lokal',	
        'pelunasan',	
        'pajak',
        'diskon',	
        'pengiriman',
        'no_box',
        'harga_hpp',
        'tipe_order'
    ];

   
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];

    public function purchaseOrder()
    {
        return $this->belongsTo(PurchaseOrder::class);
    }

      protected static function boot()
    {
        parent::boot();

        // Auto generate invoice number sebelum create
        static::creating(function ($model) {
            if (empty($model->no_po) || $model->no_po === "Generated By System") {
                $model->no_po = $model->generatePurchaseOrderNumber($model->tipe_order);
            }
        });
    }

    public function generatePurchaseOrderNumber(string $orderType): string
    {
        // Validasi tipe order
        $validOrderTypes = ['01', '02', '03', '04'];
        if (!in_array($orderType, $validOrderTypes)) {
            throw new \Exception("Tipe order tidak valid. Gunakan: 01, 02, 03, atau 04");
        }

        // Prefix tetap
        $prefix = "JUSA";
        
        // Tahun dan bulan sekarang
        $year = now()->format('Y');
        $month = now()->format('m');
        
        // Pattern untuk mencari invoice terakhir bulan ini
        $pattern = $prefix . $orderType . '%';
        
        // Cari invoice terakhir dengan pattern yang sama
        $lastInvoice = self::where('no_po', 'like', $pattern)
            ->orderBy('no_po', 'desc')
            ->first();
        
        // Tentukan increment number
        if ($lastInvoice && $lastInvoice->no_po) {
            $lastNumber = substr($lastInvoice->no_po, -5);
            $increment = intval($lastNumber) + 1;
        } else {
            $increment = 1;
        }
        
        // Format increment menjadi 4 digit
        $incrementFormatted = str_pad($increment, 5, '0', STR_PAD_LEFT);
        
        // Gabungkan semua bagian
        return $prefix . $orderType . $incrementFormatted;
    }
}